spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shipping}
    username: ${SPRING_DATASOURCE_USERNAME:shipping}
    password: ${SPRING_DATASOURCE_PASSWORD:shipping}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  shell:
    interactive:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
